# Generated by Django 4.2.5 on 2023-10-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RSSNews",
        ),
    ]
