# Generated by Django 4.2.5 on 2024-01-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diy', '0003_project_short_descriptionfr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='release',
        ),
        migrations.RemoveField(
            model_name='project',
            name='source',
        ),
        migrations.AddField(
            model_name='project',
            name='archive',
            field=models.FileField(blank=True, upload_to='upload/diy/archive/'),
        ),
    ]
