# Generated by Django 4.2.5 on 2023-09-23 15:02

import diy.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=2000)),
                ("short_description", models.TextField()),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "tags",
                    models.TextField(
                        blank=True, validators=[diy.models.Project.validate_tags]
                    ),
                ),
                ("authors", models.TextField()),
                ("active_developpement", models.BooleanField(default=False)),
                ("source", models.FileField(upload_to="upload/dev/sources")),
            ],
        ),
    ]
