# Generated by Django 4.2.5 on 2023-09-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questionEN", models.CharField(max_length=2000)),
                ("answerEN", models.TextField()),
                ("questionFR", models.CharField(max_length=2000)),
                ("answerFR", models.TextField()),
                ("picture", models.ImageField(blank=True, upload_to="questions/")),
            ],
        ),
        migrations.DeleteModel(
            name="FAQuestion",
        ),
        migrations.RenameField(
            model_name="presentation",
            old_name="text",
            new_name="textEN",
        ),
        migrations.AddField(
            model_name="friend",
            name="short_descriptionEN",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="friend",
            name="short_descriptionFR",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="presentation",
            name="textFR",
            field=models.TextField(default="bonjour"),
            preserve_default=False,
        ),
    ]
