# Generated by Django 4.2.5 on 2023-09-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_question_delete_faquestion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="picture",
            field=models.ImageField(blank=True, upload_to="upload/friends/"),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="picture",
            field=models.ImageField(blank=True, upload_to="upload/aboutme/"),
        ),
        migrations.AlterField(
            model_name="question",
            name="picture",
            field=models.ImageField(blank=True, upload_to="upload/questions/"),
        ),
    ]
