# Generated by Django 4.2.5 on 2023-09-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_friend_picture_alter_presentation_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactoption",
            name="discord",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
