# Generated by Django 4.2.5 on 2023-09-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_contactoption_discord"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactoption",
            name="message",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="contactoption",
            name="discord",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
