# Generated by Django 4.2.5 on 2023-09-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_contactoption_message_alter_contactoption_discord"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=200)),
                ("link", models.TextField(max_length=2000)),
                ("emphasis", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="ContactOption",
        ),
    ]
