# Generated by Django 4.2.5 on 2023-09-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_contactlink_link_alter_contactlink_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactlink",
            name="comment",
            field=models.TextField(default="so6", max_length=2000),
            preserve_default=False,
        ),
    ]
