# Generated by Django 4.2.5 on 2023-09-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_contactlink_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactlink",
            old_name="link",
            new_name="direct_link",
        ),
        migrations.AddField(
            model_name="contactlink",
            name="username",
            field=models.CharField(default="so6", max_length=200),
            preserve_default=False,
        ),
    ]
