# Generated by Django 4.2.5 on 2023-09-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_rename_message_contactmessage_messageen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactlink",
            name="commentFR",
            field=models.TextField(default="aaaaaaa", max_length=2000),
            preserve_default=False,
        ),
    ]
