# Generated by Django 4.2.5 on 2023-10-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_contactlink_commentfr"),
    ]

    operations = [
        migrations.CreateModel(
            name="TitleText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("textEN", models.TextField()),
                ("textFR", models.TextField()),
            ],
        ),
    ]
