# Generated by Django 4.2.5 on 2023-09-12 11:43

import dev.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2000)),
                ("short_description", models.TextField(blank=True)),
                ("vignette", models.ImageField(blank=True, upload_to="")),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "tags",
                    models.TextField(
                        blank=True, validators=[dev.models.Project.validate_tags]
                    ),
                ),
                ("authors", models.TextField()),
                ("languages", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=False)),
                ("source", models.FileField(upload_to="dev/")),
            ],
        ),
    ]
