# Generated by Django 4.2.5 on 2023-09-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dev", "0003_rename_active_project_active_developpement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="url",
            field=models.CharField(default="url", max_length=200),
            preserve_default=False,
        ),
    ]
