# Generated by Django 4.2.5 on 2023-09-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dev", "0004_project_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
