# Generated by Django 4.2.5 on 2023-09-05 18:47

import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("short_title", models.CharField(max_length=30, unique=True)),
                (
                    "vignette",
                    models.ImageField(blank=True, null=True, upload_to="%Y/%m"),
                ),
                (
                    "tags",
                    models.TextField(
                        blank=True, validators=[blog.models.Article.validate_tags]
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("FR", "Francais"), ("EN", "English")], max_length=10
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "visible_starting",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(blank=True)),
            ],
        ),
    ]
