# Generated by Django 4.2.5 on 2023-09-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="vignette",
            field=models.ImageField(blank=True, upload_to="art/art/"),
        ),
        migrations.AlterField(
            model_name="piece",
            name="file",
            field=models.ImageField(upload_to="upload/art/"),
        ),
    ]
