# Generated by Django 4.2.5 on 2023-09-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0002_alter_album_vignette_alter_piece_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="url",
            field=models.CharField(default="default", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="album",
            name="vignette",
            field=models.ImageField(blank=True, upload_to="upload/art/"),
        ),
    ]
