# Generated by Django 4.2.5 on 2023-09-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0003_album_url_alter_album_vignette"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="url",
            field=models.CharField(default="test", max_length=200),
            preserve_default=False,
        ),
    ]
