# Generated by Django 4.2.5 on 2023-09-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0005_remove_album_vignette"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="source_file",
            field=models.FileField(default="aa", upload_to="upload/art/sources/"),
            preserve_default=False,
        ),
    ]
