# Generated by Django 4.2.5 on 2023-09-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0010_alter_piece_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="descriptionFR",
            field=models.TextField(blank=True, help_text="Optional"),
        ),
        migrations.AddField(
            model_name="album",
            name="nameFR",
            field=models.CharField(default="so6", max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="piece",
            name="commentFR",
            field=models.TextField(blank=True, help_text="Optional"),
        ),
        migrations.AddField(
            model_name="piece",
            name="nameFR",
            field=models.CharField(default="s", max_length=2000),
            preserve_default=False,
        ),
    ]
