# Generated by Django 4.2.5 on 2024-01-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_titletext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleText',
        ),
    ]
