# Generated by Django 4.2.5 on 2023-09-12 11:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2000)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("vignette", models.ImageField(blank=True, upload_to="art/")),
                ("description", models.TextField(blank=True, help_text="Optional")),
            ],
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2000)),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("authors", models.TextField()),
                ("comment", models.TextField(blank=True, help_text="Optional")),
                ("file", models.ImageField(upload_to="art/")),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="art.album"
                    ),
                ),
            ],
        ),
    ]
