# Generated by Django 4.2.5 on 2023-09-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0006_piece_source_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="scaling_method",
            field=models.CharField(
                choices=[
                    ("auto", "auto"),
                    ("crisp-edges", "crisp-edges"),
                    ("smooth", "smooth"),
                    ("high-quality", "high-quality"),
                    ("pixelated", "pixelated"),
                ],
                default="auto",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
